TODO list/ToDoListUsingMVC/ToDoListUsingMVC/Models/TODOItem.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoListUsingMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TODOItem
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
    }
}

TODO list/ToDoListUsingMVC/ToDoListUsingMVC/Models/ToDoListModel.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoListUsingMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDBEntities : DbContext
    {
        public MyDBEntities()
            : base("name=MyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TODOItem> TODOItems { get; set; }
    }
}

TODO list/ToDoListUsingMVC/ToDoListUsingMVC/Models/ToDoListModel.Designer.cs
// T4 code generation is enabled for model 'C:\Users\nitgo\Desktop\Interview\ToDoListUsingMVC\ToDoListUsingMVC\Models\ToDoListModel.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

TODO list/ToDoListUsingMVC/ToDoListUsingMVC/Models/ToDoListModel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

TODO list/ToDoListUsingMVC/ToDoListUsingMVC/Controllers/ToDoListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToDoListUsingMVC.Models;

namespace ToDoListUsingMVC.Controllers
{
    public class ToDoListController : Controller
    {
        // GET: ToDoList
        public ActionResult Index()
        {
            List<TODOItem> todoItemList = new List<TODOItem>();
            using (MyDBEntities myDBEntity = new MyDBEntities())
            {
                todoItemList = myDBEntity.TODOItems.Where(item => item.Status == "Open").ToList();
            };
            return View(todoItemList);
        }

        
        // GET: ToDoList/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ToDoList/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                //create an object of ToDoItem
                TODOItem toDoItem = new TODOItem()
                {
                    Description = collection["Description"],
                    Status = collection["Status"]
                };
                //add new item to list;
                using (MyDBEntities myDBEntity = new MyDBEntities())
                {
                    myDBEntity.TODOItems.Add(toDoItem);
                    myDBEntity.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                return View();
            }
        }

       
        [HttpPost]
        public ActionResult Edit(FormCollection formCollection)
        {
            try
            {
               MyDBEntities myDBEntity = new MyDBEntities();

                string[] idArray = new string[] { }; 
                string[] statusArray = new string[] { };
                
                foreach (string key in formCollection.AllKeys)
                {
                    //retrieve id and status values from form array
                    if (key.Contains("itemChk"))
                    {
                        statusArray = formCollection[key].Replace("true,false","true").Split(',');
                    }
                    else if (key.Contains("Id"))
                    {
                        idArray = formCollection[key].Split(',');
                    }
                }
                //iterate thru status array as it will always have highest values.
                int lentgh = statusArray.Length;
                if (lentgh > 0)
                {
                    for (int i = 0; i < statusArray.Length; i++)
                    {
                        int ID = Convert.ToInt32(idArray[i]);
                        if (statusArray[i].ToLower() == "true")
                        {
                            TODOItem tODOItem = myDBEntity.TODOItems.SingleOrDefault(item => item.Id == ID);
                            tODOItem.Status = "Completed";
                        }
                    }
                }
                myDBEntity.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Error");
            }
        }

        
        public ActionResult Delete(int id)
        {
            try
            {
                using (MyDBEntities myDBEntity = new MyDBEntities())
                {
                    //get item from list by id
                    TODOItem tODOItem = myDBEntity.TODOItems.FirstOrDefault(tdi => tdi.Id == id);
                    if(tODOItem != null)
                    {
                        myDBEntity.TODOItems.Remove(tODOItem);
                        myDBEntity.SaveChanges();
                    }
                };
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Index");
            }
        }
    }
}

TODO list/ToDoListUsingMVC/ToDoListUsingMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>

</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>
</body>
@RenderSection("scripts", required: false);
</html>

TODO list/ToDoListUsingMVC/ToDoListUsingMVC/Views/ToDoList/Create.cshtml
@model ToDoListUsingMVC.Models.TODOItem

@{
    ViewBag.Title = "Add New TO DO Item";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h2>Add New TO DO Item</h2>


@using (Html.BeginForm("Create","ToDoList",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ToDoItem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TODO list/ToDoListUsingMVC/ToDoListUsingMVC/Views/ToDoList/Index.cshtml
@model IEnumerable<ToDoListUsingMVC.Models.TODOItem>

@{

    ViewBag.Title = "Your TODO List";
    Layout = "~/Views/Shared/_Layout.cshtml";

} 
 
@using (Html.BeginForm("Edit", "ToDoList",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    

    <div class="row">
        <h2>To Do List</h2>
        <div class="col col-md-6">
            <div class="panel panel-primary list-panel" id="list-panel">

                <div class="panel-body">
                    <table class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th>Desription</th>
                                <th>Done with it?</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.HiddenFor(modelItem => item.Id)
                                        @Html.DisplayFor(modelitem => item.Description)</td>
                                    <td>
                                        @Html.CheckBox("itemChk",false)
                                        @Html.HiddenFor(modelitem => item.Status)
                                        @Html.ActionLink("Remove", "Delete", new { id = item.Id })
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                    <div class="text-center">
                        <!-- invoke Action Create() in TodOListController controller-->
                        <a href="@Url.Action("Create", "ToDoList")" class="btn btn-primary">Add New</a>
                        <input type="submit" class="btn btn-success" value="Status Update"/>
                    </div>
                </div>
            </div>
        </div>
    </div>
 }

TODO list/ToDoListUsingMVC/ToDoListUsingMVC/Views/Update.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>